# Generated by Django 4.2 on 2023-05-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
