# Generated by Django 4.2 on 2023-05-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("variation1", models.CharField(blank=True, max_length=100)),
                ("variation2", models.CharField(blank=True, max_length=100)),
                ("condition", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("photos", models.ImageField(upload_to="products/")),
            ],
        ),
    ]
