# Generated by Django 4.2 on 2023-05-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
