# Generated by Django 4.2 on 2023-05-23 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0007_delete_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variation1", models.CharField(blank=True, max_length=100, null=True)),
                ("variation2", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("P", "Perfect"),
                            ("E", "Excellent"),
                            ("G", "Good"),
                            ("F", "Fair"),
                        ],
                        max_length=1,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("photos", models.ImageField(upload_to="assets/images")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.brand"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.category"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
