# Generated by Django 4.2 on 2023-05-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_rename_brand_product_brand_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="brand_id",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="category_id",
            new_name="category",
        ),
    ]
