# Generated by Django 4.2 on 2023-05-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_alter_product_photos_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photos",
            field=models.ImageField(upload_to="images"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
