# Generated by Django 4.2 on 2023-05-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_product_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[
                    ("Perfect", "Perfect"),
                    ("Excellent", "Excellent"),
                    ("Good", "Good"),
                    ("Fair", "Fair"),
                ],
                max_length=10,
            ),
        ),
    ]
