# Generated by Django 4.2 on 2023-05-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_alter_product_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[
                    ("Perfect- Never been used and no blemishes", "Perfect"),
                    ("Excellent- A few minor cosmetic issues", "Excellent"),
                    ("Good- Some dings and scratches", "Good"),
                    ("Fair- Extensive cosmetic issues", "Fair"),
                ],
                max_length=100,
            ),
        ),
    ]
