# Generated by Django 4.2 on 2023-05-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_alter_product_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[
                    ("Perfect", "- Never been used and no blemishes"),
                    ("Excellent", "- A few minor cosmetic issues"),
                    ("Good", "- Some dings and scratches"),
                    ("Fair", "- Extensive cosmetic issues"),
                ],
                max_length=100,
            ),
        ),
    ]
