# Generated by Django 4.2 on 2023-05-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_alter_product_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[
                    ("Perfect", "- never been used and no blemishes"),
                    ("Excellent", "- a few minor cosmetic issues"),
                    ("Good", "- some dings and scratches"),
                    ("Fair", "- extensive cosmetic issues"),
                ],
                max_length=100,
            ),
        ),
    ]
