# Generated by Django 4.2 on 2023-05-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_alter_product_condition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="photos",
        ),
    ]
