# Generated by Django 4.2 on 2023-05-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_remove_product_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photos",
            field=models.ImageField(default="test", upload_to="images"),
            preserve_default=False,
        ),
    ]
