# Generated by Django 4.2 on 2023-05-25 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0025_remove_profile_id_alter_profile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="TackleShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(max_length=200)),
                ("shop_url", models.URLField()),
                ("shop_logo", models.ImageField(upload_to="shop_logos")),
                ("address_line1", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("county", models.CharField(max_length=200)),
                ("postcode", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
