# Generated by Django 4.2 on 2023-05-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0027_offer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="photos",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.product"
            ),
        ),
    ]
