# Generated by Django 4.2 on 2023-05-27 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0028_remove_product_photos_alter_productimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photos",
            field=models.ImageField(default=1, upload_to="images"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="myapp.product",
            ),
        ),
    ]
