# Generated by Django 4.2 on 2023-05-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0029_product_photos_alter_productimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photos2",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="product",
            name="photos3",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="product",
            name="photos4",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
