# Generated by Django 4.2 on 2023-05-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0031_remove_product_photos_remove_product_photos2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
