# Generated by Django 4.2 on 2023-05-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0032_offer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(default=7945863, max_length=20),
            preserve_default=False,
        ),
    ]
