# Generated by Django 4.2 on 2023-06-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0034_alter_profile_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="price",
            new_name="cash_price",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="shipping_included",
        ),
        migrations.AddField(
            model_name="offer",
            name="trade_in_price",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
    ]
